export const GET_POST = "GET_POST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const CREATE_POSTS = "CREATE_POSTS";
export const CREATE_POSTS_SUCCESS = "CREATE_POSTS_SUCCESS";
export const CREATE_POSTS_FAILURE = "CREATE_POSTS_FAILURE";

export const DELETE_POSTS = "DELETE_POSTS";
export const DELETE_POSTS_SUCCESS = "DELETE_POSTS_SUCCESS";
export const DELETE_POSTS_FAILURE = "DELETE_POSTS_FAILURE";

export const UPDATE_POSTS = "UPDATE_POSTS";
export const UPDATE_POSTS_SUCCESS = "UPDATE_POSTS_SUCCESS";
export const UPDATE_POSTS_FAILURE = "UPDATE_POSTS_FAILURE";

export const UPDATE_SINGLE_POST= "UPDATE_SINGLE_POST";


export const LIKE_POSTS = "LIKE_POSTS";
export const LIKE_POSTS_SUCCESS = "LIKE_POSTS_SUCCESS";
export const LIKE_POSTS_FAILURE = "LIKE_POSTS_FAILURE";